name: Build and Test
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  report:
    name: Report
    runs-on: ubuntu-latest
    steps:
      - name: ref
        run: echo ${{ github.ref }}
      - name: event_name
        run: echo ${{ github.event_name }}
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          # Fetch the last 2 commits instead of just 1.
          # Needed for adding the amended commit with the language bindings
          # (Fetching just 1 commit would overwrite the whole history)
          fetch-depth: 2
      - uses: arduino/setup-protoc@v2
        with:
          version: '21.9'
          repo-token: ${{ secrets.GITHUB_TOKEN }}          
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.20
      - name: install protodot
        run: go install github.com/seamia/protodot@v1.2.0
      - name: install protoc-gen-go
        run: go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1
      - name: make
        run: make proto
      - name: Get last commit message
        id: last-commit-message
        run: |
          echo "msg=$(git log -1 --pretty=%s)" >> $GITHUB_OUTPUT
      - name: commit the changes
        uses: stefanzweifel/git-auto-commit-action@v4          
        with:
          commit_message: ${{ steps.last-commit-message.outputs.msg }}
          commit_options: '--amend --no-edit'
          push_options: '--force'
          skip_fetch: true
      
